### ISSUE TITLE
Raba crashed when adding the same Run Action into a macro

### ISSUE THREAD

**Issue by thanhngo** [thanhngo/raba#8]
After restart, Raba can not load Actions from macro file.

![image](https://user-images.githubusercontent.com/5762913/117400959-83009100-aeb8-11eb-8a28-baa61a9faef9.png)

**Comment by thanhngo** [comment]
Event Log:

`Application: RabaMetroStyle.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Data.DataRow.GetDataColumn(System.String)
   at System.Data.DataRow.set_Item(System.String, System.Object)
   at RabaMetroStyle.ViewModels.SettingsViewModel.AddMacroAction()
   at RabaMetroStyle.Mvvm.DelegateCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at RabaMetroStyle.App.Main()

`

**Comment by thanhngo** [comment]
Macro file:

`<?xml version="1.0" standalone="yes"?>
<NewDataSet>
  <tblTaskInfo>
    <ScanLocation>C:\Users\Thanh\Downloads\unikey43RC5-200929-win64</ScanLocation>
    <IncludeSubFolders>False</IncludeSubFolders>
    <ScanFileExtension />
    <ScanFilePrefix />
    <ScanFileDateLessThan>1/1/2070</ScanFileDateLessThan>
    <ScanFileDateGreaterThan>1/1/1970</ScanFileDateGreaterThan>
    <ScanFileUseRelativeAgeYounger>False</ScanFileUseRelativeAgeYounger>
    <ScanFileAgeYounger>-1</ScanFileAgeYounger>
    <ScanFileUseRelativeAgeOlder>False</ScanFileUseRelativeAgeOlder>
    <OnlyCountWeekDays>False</OnlyCountWeekDays>
    <ScanFileAgeOlder>-1</ScanFileAgeOlder>
    <ScanFileSizeLessThan>0</ScanFileSizeLessThan>
    <ScanFileSizeGreaterThan>0</ScanFileSizeGreaterThan>
    <Action>COPY</Action>
    <ActionCompleteRename>False</ActionCompleteRename>
    <ActionCompleteTimeStamp>False</ActionCompleteTimeStamp>
    <ActionCompleteDelete>False</ActionCompleteDelete>
    <TargetLocation>C:\Users\Thanh\Downloads</TargetLocation>
    <MaintainSubFolders>False</MaintainSubFolders>
    <Command />
    <IntegratedSecurity>True</IntegratedSecurity>
    <UserID />
    <Password />
    <DatabaseName />
    <DatabaseServer />
    <TaskOrder>1</TaskOrder>
    <RunSQLScript>False</RunSQLScript>
    <RunSQLScriptFilePath />
    <RestoreDatabaseFileGroups />
  </tblTaskInfo>
  <tblTaskInfo>
    <ScanLocation>C:\Users\Thanh\Downloads</ScanLocation>
    <IncludeSubFolders>False</IncludeSubFolders>
    <ScanFileExtension />
    <ScanFilePrefix />
    <ScanFileDateLessThan>1/1/2070 12:00:00 AM</ScanFileDateLessThan>
    <ScanFileDateGreaterThan>1/1/1970 12:00:00 AM</ScanFileDateGreaterThan>
    <ScanFileUseRelativeAgeYounger>False</ScanFileUseRelativeAgeYounger>
    <ScanFileAgeYounger>-1</ScanFileAgeYounger>
    <ScanFileUseRelativeAgeOlder>False</ScanFileUseRelativeAgeOlder>
    <OnlyCountWeekDays>False</OnlyCountWeekDays>
    <ScanFileAgeOlder>-1</ScanFileAgeOlder>
    <ScanFileSizeLessThan>0</ScanFileSizeLessThan>
    <ScanFileSizeGreaterThan>0</ScanFileSizeGreaterThan>
    <Action>RUN</Action>
    <ActionCompleteRename>False</ActionCompleteRename>
    <ActionCompleteTimeStamp>False</ActionCompleteTimeStamp>
    <ActionCompleteDelete>True</ActionCompleteDelete>
    <TargetLocation />
    <MaintainSubFolders>False</MaintainSubFolders>
    <Command />
    <IntegratedSecurity>True</IntegratedSecurity>
    <UserID />
    <Password />
    <DatabaseName />
    <DatabaseServer />
    <TaskOrder>2</TaskOrder>
    <RunSQLScript>False</RunSQLScript>
    <RunSQLScriptFilePath />
    <RestoreDatabaseFileGroups />
  </tblTaskInfo>
</NewDataSet>`

**Comment by thanhngo** [comment]
Reproduce:

1. Create macro file.
2. Add Run Action. Tick Conditional Run Child and Save.
3. Open Run Action. Untick Conditional Run Child and Save.
4. Close Raba and reopen.
